---
- name: Execute Bash Script and Set Up Cron Job on Slave
  hosts: 192.168.33.12
  become: yes
  tasks:
    - name: update & upgrade server
      apt:
        update_cache: yes
        upgrade: yes

    - name: Execute Bash Script
      script: /home/vagrant/Ansible-playbook/master-setup.sh
      register: script_output
      ignore_errors: yes

    - name: Verify Application Accessibility
      uri:
        url: http://192.168.33.11   
        status_code: 200
      ignore_errors: yes

    - name: Create a cron job to check server uptime at 12 am
      cron:
        name: Check Uptime
        job: "/usr/bin/uptime > /var/log/uptime.log"
        minute: 0
        hour: 0
